---
title       : Reproducible Pitch
subtitle    : Week 4
author      : Niraj Nair
job         : 24 July, 2020
framework   : io2012        # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : tomorrow      # 
widgets     : [mathjax, quiz, bootstrap]            # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}
knit        : slidify::knit2slides
---

## Project Goals

This peer assessed assignment has two parts.First, you will create a Shiny application and deploy it on Rstudio's servers.Second, you will use Slidify or Rstudio Presenter to prepare a reproducible pitch presentation about your application.

---

## Steps to Perform

Steps to Perform
+ Write a shiny application with associated supporting documentation. The documentation should be thought of as whatever a user will need to get started using your application.
+ Deploy the application on Rstudio's shiny server.
+ Share the application link by pasting it into the provided text box.
+ Share your server.R and ui.R code on github.

---

## How to use the application

Enter your weight and height in the text field and you can find your BMI index.

The application is running [here](https://nirajnair.shinyapps.io/shiny_app/).

ui.R, and Server.R Code are in my github repository.
You can find out [here](https://github.com/NirajNair/Shiny-App).

Codes for these slides are [here](https://github.com/NirajNair/Reproducible-Pitch)

---
## BMI calculator
Body mass index: A key index for relating weight to height. Abbreviated BMI. The National Institutes of Health (NIH) now defines normal weight, overweight, and obesity according to BMI rather than the traditional height/weight charts.

--- 

## How to calculate BMI?

BMI is a person's weight in kilograms (kg) divided by his or her height in meters squared.
```{r bmiCalc}
height = 180 #in cm 
weight = 70 #in kg
bmi_cal= (weight / height^2) * 10000
bmi_cal
```

---
    
## BMI Scale

+ If BMI is less than 18.5 you are considered UNDERWEIGHT.
+ If BMI is in range 18.5 to 24.9 you are in HEALTHY WEIGHT RANGE.
+ If BMI is in range 25 to 29.9 you are OVERWEIGHT.
+ If BMI is higher than 30 you are OBESE.


